src/ProgDBTutor/views/friends.py
from flask import Blueprint, redirect, url_for, render_template, request, jsonify, current_app
from flask_login import login_required, current_user

from config import config_data

from models.friendship import Friendship
from models.chatmessage import ChatMessage


friends_blueprint = Blueprint('friends', __name__, template_folder='templates')


@friends_blueprint.route('/dashboard')
@login_required
def dashboard():
    """
    Renders the dashboard view, for a user.
    """
    if current_user.username == 'admin':
        return redirect(url_for('admin'))
    return render_template('friends/dashboard.html', app_data=config_data)

@friends_blueprint.route('/search_friends')
@login_required
def search_friends():
    """
    Renders the search friends view, for a user.
    """
    query = request.args.get('query', '')
    if query:
        user_data_access = current_app.config.get('user_data_access')
        matching_users = user_data_access.search_users(query)
        matching_users_not_friends = []
        for user in matching_users:
            friendship_data_access = current_app.config.get('friendship_data_access')
            if not friendship_data_access.get_friendship(current_user, user):
                matching_users_not_friends.append(user)
    else:
        matching_users_not_friends = []
    return render_template('friends/friends_search_results.html', users=matching_users_not_friends, app_data=config_data)


@friends_blueprint.route('/add_friend/<string:friend_name>', methods=['POST'])
@login_required
def add_friend(friend_name):
    """
    Handles POST requests for adding a friend
    :param friend_name: The name of the friend
    :return: Redenders the dashboard view
    """
    user_data_access = current_app.config.get('user_data_access')
    user_1 = user_data_access.get_user(current_user.username)
    user_2 = user_data_access.get_user(friend_name)
    friendship_data_access = current_app.config.get('friendship_data_access')
    friendship_data_access.add_friendship(Friendship(user_1, user_2))

    return render_template('friends/dashboard.html',  app_data=config_data)

@friends_blueprint.route('/add_message', methods=['POST'])
@login_required
def add_message():
    """
    Handles POST requests for adding a message
    """
    chatmessage_data_access = current_app.config.get('chatmessage_data_access')
    data = request.get_json()
    sender = current_user.username
    receiver = data['receiver']
    message = data['message']
    # Assuming the add_message method returns a boolean indicating success
    if chatmessage_data_access.add_message(ChatMessage(sender, receiver, message)):
        return jsonify({'status': 'success', 'message': 'Message sent successfully.'})
    else:
        return jsonify({'status': 'error', 'message': 'Failed to send message.'}), 500

@friends_blueprint.route('/visit_friend_world/<string:friend_name>', methods=['GET'])
@login_required
def visit_friend(friend_name):
    """
    Renders the visit friend view, for a user. This allows the user to visit a friend's world.
    """
    user_data_access = current_app.config.get('user_data_access')
    friend = user_data_access.get_user(friend_name)

    return render_template('friends/visit_friend.html', friend=friend, app_data=config_data)

src/ProgDBTutor/templates/friends/chat_window.html
<!-- Chat Column -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script type="module" src="{{ url_for('static', filename='js/settings.js') }}"></script>
    <script type="module" src="{{ url_for('static', filename='js/sound.js') }}"></script>
    <!-- Bootstrap CSS -->


    <style>

    .custom-chat-window {
        height: 500px;
        width: 700px;
        margin-bottom: 10px;
        margin-top:50px;
    }

    .custom-chat-body {
        overflow-y: scroll;
    }

    .custom-card-footer {
        border-top: 1px solid #ccc;
    }

    .custom-input {
        border-radius: 20px; /* Example of customizing input field */
    }
    .custom-header {
        background-image: url('../../static/img/background/wood.png');
        background-size: cover;
        color: wheat;

    }
     .btn-custom-search{
            background-image: url('../../static/img/background/button-image.png');
            color:wheat;
     }

     .custom-chat-window.card {
            border-radius: 20px; /* Set border-radius to 20px for rounded corners */
     }
     .custom-chat-window{
         background-color: papayawhip;
     }

     .card-header{
         border-radius: 20px;
     }


    button:active {
    cursor: url('../../static/img/UI/pointer_click.png'), auto;
}
    img:hover {
    cursor: url('../../static/img/UI/pointer_hover.png'), auto;
    }

    body{
         cursor: url('../../static/img/UI/cursor.png'), auto;
    }
    </style>





</head>
<body>

<div class="col-md-8">
    <div class="card border chat-window custom-chat-window" >

        <div class="card-header custom-header text-white" id="chat-header">
            Chat with <span id="chat-with-name">...</span>
            <!-- The 'Visit World' button will be added here by JavaScript -->
        </div>

        <div id="chat-messages" class="chat-messages card-body custom-chat-body">
            <!-- Messages will be dynamically loaded here -->
        </div>
        <form id="send-message-form" class="card-footer custom-card-footer">
            <input type="hidden" name="receiver" id="receiver" value="">
            <div class="input-group">
                <input type="text" name="message" id="message-input" class="form-control custom-input" placeholder="Type a message..." required>
                <div class="input-group-append">
                    <button type="button" id="send-message-btn" class="btn btn-custom-search" style="cursor: url('../../static/img/UI/pointer_click.png'), auto;">Send</button>
                </div>
            </div>
        </form>
    </div>
</div>


<script>

    localStorage.getItem('muteButtonState')
    localStorage.getItem('backsoundButtonState')
    // Function to load chat messages
    function loadChat(friend_name) {
        // Here you would make an API call to fetch the chat messages
        // For this example, we're just updating the chat window title
        const chatWithName = document.getElementById('chat-with-name');
        chatWithName.textContent = friend_name;

        const receiver = document.getElementById('receiver');
        receiver.value = friend_name;

        // Remove any existing 'Visit World' button
        const existingButton = document.getElementById('visit-friends-world-btn');
        if (existingButton) {
            existingButton.remove();
        }

        // Create the 'Visit World' button
        const visitWorldButton = document.createElement('button');
        visitWorldButton.id = 'visit-friends-world-btn';
        visitWorldButton.textContent = 'Visit World';
        visitWorldButton.className = 'btn btn-custom-search';
        visitWorldButton.style.float = 'right';
        visitWorldButton.style.cursor = 'url("../../static/img/UI/pointer_click.png"), auto';
        visitWorldButton.onclick = visitFriendsWorld; // Assuming you've defined this function


        // Append the button to the header
        const chatHeader = document.getElementById('chat-header');
        chatHeader.appendChild(visitWorldButton);

        function fetchAndUpdateMessages() {
            // Clear previous messages
            const chatMessages = document.getElementById('chat-messages');
            chatMessages.innerHTML = ''; // Use innerHTML to clear the messages

            // Fetch messages and populate `chatMessages`
            fetch(`/api/messages/${friend_name}`) // This should be the URL to your API endpoint for fetching messages
                .then(response => response.json())
                .then(messages => {
                    // Assuming 'messages' is sorted by 'created_at' in ascending order
                    let lastMessageDate = null;

                    messages.forEach((msg, index) => {
                        const currentDate = new Date(msg.created_at);

                        // Create elements for the message and its timestamp
                        const messageDiv = document.createElement('div');
                        const messageContent = document.createElement('p');
                        messageContent.textContent = msg.message;
                        messageDiv.className = msg.sender === friend_name ? 'received' : 'sent';

                        // Append the message text to the message div
                        messageDiv.appendChild(messageContent);

                        // Check if there's a need to insert a timestamp divider
                        if (lastMessageDate) {
                            const hourDifference = Math.abs(currentDate - lastMessageDate) / 36e5;
                            if (hourDifference >= 1) {
                                // Insert timestamp divider
                                const timeDivider = document.createElement('div');
                                timeDivider.className = 'time-divider';
                                timeDivider.textContent = lastMessageDate.toLocaleString('en-US', { hour: 'numeric', minute: 'numeric', hour12: true });
                                chatMessages.appendChild(timeDivider);
                            }
                        }

                        // Append the current message
                        chatMessages.appendChild(messageDiv);

                        // Update lastMessageDate with the current message's date
                        lastMessageDate = currentDate;

                        // For the last message in the array, also append a timestamp divider
                        if (index === messages.length - 1) {
                            const timeDivider = document.createElement('div');
                            timeDivider.className = 'time-divider';
                            timeDivider.textContent = currentDate.toLocaleString('en-US', { hour: 'numeric', minute: 'numeric', hour12: true });
                            chatMessages.appendChild(timeDivider);
                        }
                    });


                })
                .catch(error => console.error('Error fetching messages:', error));
            }
            fetchAndUpdateMessages();
            setInterval(fetchAndUpdateMessages, 5000); // Refresh messages every 5 seconds
    }

    // AJAX call to send a message
    function sendMessage() {
        const receiver = document.getElementById('receiver').value;
        const message = document.getElementById('message-input').value;

        fetch('{{ url_for("friends.add_message") }}', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                receiver: receiver,
                message: message
            }),
        })
        .then(response => {
            if (!response.ok) {
                throw new Error('Network response was not ok');
            }
            return response.json();
        })
        .then(data => {
            console.log('Message sent:', data);
            document.getElementById('message-input').value = '';
            const chatMessages = document.getElementById('chat-messages');
            const messageDiv = document.createElement('div');
            messageDiv.className = 'sent';
            messageDiv.textContent = message;
            chatMessages.appendChild(messageDiv);
        })
        .catch(error => {
            console.error('Error:', error);
        });
    }

    document.addEventListener('DOMContentLoaded', function() {
        document.getElementById('send-message-btn').addEventListener('click', sendMessage);
        document.getElementById('message-input').addEventListener('keydown', function(event) {
            if (event.key === 'Enter') {
                event.preventDefault();
                sendMessage();
            }
        });
    });

    // Function to handle the 'Visit World' action
    function visitFriendsWorld() {
        const friendName = document.getElementById('receiver').value;
        // Here you would either navigate to the world or make an API call
        console.log(`Visiting ${friendName}'s world...`);
        window.location.href = `/friends/visit_friend_world/${friendName}`;
        // Example: window.location.href = `/world/${friendName}`;
    }

</script>
</body>
</html>

src/ProgDBTutor/templates/friends/dashboard.html
<!DOCTYPE html>
<html lang="">
<head>
    <title>Dashboard - {{ app_data['app_name'] }}</title>
    <script type="module" src="{{ url_for('static', filename='js/settings.js') }}"></script>
    <script type="module" src="{{ url_for('static', filename='js/sound.js') }}"></script>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/header&footer.css') }}">

    {% include 'head.html' %}

    <style>

        body {
            background-image: url("../../static/img/background/terrain.png");  /* or different image: ../../static/img/backround_dashboard.png  */
             image-rendering: pixelated;



        }

    </style>
</head>
<body>
    <header>
        <button id="back-btn" class="back-btn">
            <a href="{{ url_for('main') }}">
                <img src="{{ url_for('static', filename='img/UI/back_btn.png') }}" alt="Back">
            </a>
        </button>
        <button id="back-btn" class="farmclash-btn">
            <a href="{{ request.path }}">
                <img src="{{ url_for('static', filename='img/UI/FarmClash_btn.png') }}" alt="{{ app_data['app_name'] }}">
            </a>
        </button>
    </header>

  <div class="container-fluid mt-5">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <h1 class="text-center"><img src="../../static/img/UI/Friends_tab.png"></h1>
            <div class="row">
                <!-- Friends Column -->
                {% include 'friends/friends_list.html' %}
                <!-- Chat Column -->
                {% include 'friends/chat_window.html' %}
                <!-- Profile Column
                <div class="col-md-4">
                     include 'profile/profile.html'
                </div>-->
            </div>

        </div>
    </div>
</div>
    <script>
        // Automatically load friends when the page loads
        document.addEventListener('DOMContentLoaded', function() {
            loadFriends();
        });
    </script>
</body>
</html>

src/ProgDBTutor/templates/friends/friends_list.html
<!-- Friends List -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <script type="module" src="{{ url_for('static', filename='js/settings.js') }}"></script>
     <script type="module" src="{{ url_for('static', filename='js/sound.js') }}"></script>
    <!-- Bootstrap CSS -->

    <style>



    body{
         cursor: url('../../static/img/UI/cursor.png'), auto;
    }

        #friends-column {
            margin-bottom: 10px;
            margin-top: 50px;

        }
        .custom-header{

            background-image: url('../../static/img/background/wood.png');
            background-size: cover;
            color: wheat /* Optionally, set the text color to contrast with the background */

        }
        .btn-custom-search{
            background-image: url('../../static/img/background/button-image.png');

            color:wheat;
        }
        .card-body{
            background-color: papayawhip;
        }
        .col-md-4 .card{
         border-color: papayawhip;
                                                       //TODO: border-radius fixen
        }

    </style>



</head>
<body>

<div class="col-md-4" id="friends-column">
    <div class="card">
        <div class="card-header custom-header text-white">Friends</div>
        <div class="card-body">
            <!-- Search Box -->
            <form action="{{ url_for('friends.search_friends') }}" method="get" class="mb-3">
                <div class="input-group">
                    <input type="text" class="form-control" name="query" placeholder="Search...">
                    <button class="btn btn-custom-search" type="submit" id="button-addon2" style="cursor: url('../../static/img/UI/pointer_click.png'), auto;">Search</button>
                </div>
            </form>
            <!-- Friends List -->
            <ul id="friends-list" class="list-group" >
                <!-- Friends will be loaded here by the JavaScript function -->
            </ul>
        </div>
    </div>
</div>

<script>
    localStorage.getItem('muteButtonState')
    localStorage.getItem('backsoundButtonState')
    // Function to load friends from the API
    function loadFriends() {
        fetch('/api/friends')
            .then(response => {
                if (!response.ok) {
                    throw new Error('Network response was not ok ' + response.statusText);
                }
                return response.json();
            })
            .then(friends => {
                const friendsList = document.getElementById('friends-list');
                friendsList.innerHTML = ''; // Clear the list
                friends.forEach(friend => {
                    const listItem = document.createElement('li');
                    listItem.className = 'list-group-item clickable';
                    listItem.textContent = friend;
                    // Optionally, you can add a link to view the friend's profile or initiate chat
                    listItem.onclick = function() { loadChat(friend); }; // Load chat when friend is clicked
                    friendsList.appendChild(listItem);
                });
            })
            .catch(error => console.error('Error fetching friends:', error));
    }

    // Call the loadFriends function on page load
    document.addEventListener('DOMContentLoaded', loadFriends);
</script>
</body>
</html>

src/ProgDBTutor/templates/friends/friends_search_results.html
<!DOCTYPE html>
<html lang="">
<head>
    <title>Search Results</title>
    {% include 'head.html' %}
    <link rel="stylesheet" type="text/css" href="../static/css/UI.css">
</head>
<body>
    {% include 'header&footer.html' %}

    <div class="container" style="position: absolute; text-align: center; top: 50%; left: 50%; width: 50%; transform: translate(-50%, -50%);">
        <h2>Search Results</h2>
        {% if users %}
            <ul class="list-group">
                {% for user in users %}
                    <!-- Use d-flex justify-content-between to align items to the sides -->
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        {{ user.username }}
                        <!-- Form aligned to the right -->
                        <form action="{{ url_for('friends.add_friend', friend_name=user.username) }}" method="post">
                            <button type="submit" class="btn btn-primary" style="cursor: url('../../static/img/UI/pointer_click.png'), auto;">Add as Friend</button>
                        </form>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No matching users found.</p>
        {% endif %}
        <div class="my-3">
            <a href="{{ url_for('friends.dashboard') }}" >Return to Dashboard</a>
        </div>
    </div>

</body>
</html>

src/ProgDBTutor/templates/friends/visit_friend.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Visit {{ friend['username'] }}'s World - {{ app_data['app_name'] }}</title>
    {% include 'head.html' %}
    <style>
        canvas {
            margin: 0;
            image-rendering: pixelated;
            position: absolute;
            top: 0;
            left: 0;
        }

        body {
            overflow: hidden;
            margin: 0;
        }

        #canvasContainer {
            position: relative;
        }

        #canvasContainer {
            position: relative;
        }

        #buildingCanvas {
            z-index: 2;
            <!--border: solid red;-->
        }
        #terrainCanvas {
            z-index: 1;
            <!--border: solid black;-->
        }

        /* Loading screen styles */
        #loadingScreen {
            position: fixed;
            width: 100%;
            height: 100%;
            background: rgba(0, 0, 0, 0.8);
            color: white;
            display: flex;
            justify-content: center;
            align-items: center;
            z-index: 1000;
            animation: backgroundPulse 3s infinite;
        }

        #loadingScreen h1 {
            color: white;
            animation: typing 4s steps(40, end) forwards, blink 0.75s step-end infinite;
            white-space: nowrap;
            overflow: hidden;
            border-right: 3px solid transparent;
        }

        @keyframes typing {
            from { width: 0; }
            to { width: 40ch; }
        }

        @keyframes blink {
            from, to { border-color: transparent; }
            50% { border-color: white; }
        }

        @keyframes backgroundPulse {
            0% { background-color: rgba(0, 0, 0, 0.8); }
            50% { background-color: rgba(0, 0, 0, 0.6); }
            100% { background-color: rgba(0, 0, 0, 0.8); }
        }

        .hidden {
            display: none !important;
        }
    </style>

</head>
<body>

    <!-- Loading Screen -->
    <div id="loadingScreen">
        <h1>Loading {{ friend['username'] }}'s world. Please wait...</h1>
    </div>

    {% include 'game/visit_friend_UI.html' %} <!-- This would be a new include for the UI when visiting -->

    {% include 'game/pop-up.html' %}

    <div id="canvasContainer">
        <canvas id="uiCanvas"></canvas>
        <canvas id="cropCanvas"></canvas>
        <canvas id="buildingCanvas"></canvas>
        <canvas id="terrainCanvas"></canvas>
    </div>

    <!-- When visiting a friend's world -->
<script id="dataScript" type="module" data-friend="{{ friend['username'] | string }}" src="{{ url_for('static', filename='js/canvas.js') }}"></script>
<script>
    // Attach friend to the window object to make it globally accessible
    window.friend = document.getElementById('dataScript').getAttribute('data-friend');
    console.log(window.friend);
</script>

<script>
    function hideLoadingScreen() {
        document.getElementById('loadingScreen').classList.add('hidden');
    }
</script>


</body>
</html>