src/ProgDBTutor/views/auth.py
from flask import Blueprint, render_template, request, redirect, url_for, current_app
from flask_login import login_user, logout_user, login_required

from models.user import User
from extensions import login_manager, werkzeug_check_password_hash
from config import config_data
from services.game_services import GameServices

auth_blueprint = Blueprint('auth', __name__, template_folder='templates')


@auth_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    error_message = None
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')

        user_data_access = current_app.config.get('user_data_access')
        user_record = user_data_access.get_user(username)

        if user_record and user_record.username == 'admin':
            login_user(user_record)
            return redirect(url_for('admin'))

        if user_record and werkzeug_check_password_hash(user_record.password, password):
            login_user(user_record)
            return redirect(url_for('game.game'))
        else:
            error_message = 'Invalid username or password.'
    return render_template('auth/login.html', error_message=error_message, app_name=config_data['app_name'])


@auth_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    error_message = None
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        email = request.form.get('email')  # Assuming you're collecting email too

        user_data_access = current_app.config.get('user_data_access')
        success = user_data_access.add_user(User(username, password, email))

        if success:
           # TODO: Send confiration e-mail
            gameservices = GameServices(user_data_access, current_app.config.get('map_data_access'), current_app.config.get('tile_data_access'),current_app.config.get('resource_data_access'), current_app.config.get('animal_data_access'), current_app.config.get('building_data_access'))
            gameservices.create_default_map(username)
            gameservices.initialize_resources(username)
            gameservices.initialize_animals(username)
            return redirect(url_for('auth.welcome'))
        else:
            error_message = 'Failed to register user, try a different username.'

    return render_template('auth/register.html', error_message=error_message, app_name=config_data['app_name'])


@auth_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


@auth_blueprint.route('/welcome')
def welcome():
    return render_template('auth/welcome_screen.html', app_name=config_data)

src/ProgDBTutor/views/books.py
from flask import Blueprint, redirect, url_for, render_template, request, jsonify, current_app
from flask_login import login_required, current_user


book_blueprint = Blueprint('books', __name__, template_folder='templates')

@book_blueprint.route('/book')
@login_required
def book():
    return render_template('books/book.html')

src/ProgDBTutor/views/friends.py
from flask import Blueprint, redirect, url_for, render_template, request, jsonify, current_app
from flask_login import login_required, current_user

from config import config_data

from models.friendship import Friendship
from models.chatmessage import ChatMessage


friends_blueprint = Blueprint('friends', __name__, template_folder='templates')


@friends_blueprint.route('/dashboard')
@login_required
def dashboard():
    """
    Renders the dashboard view, for a user.
    """
    if current_user.username == 'admin':
        return redirect(url_for('admin'))
    return render_template('friends/dashboard.html', app_data=config_data)

@friends_blueprint.route('/search_friends')
@login_required
def search_friends():
    """
    Renders the search friends view, for a user.
    """
    query = request.args.get('query', '')
    if query:
        user_data_access = current_app.config.get('user_data_access')
        matching_users = user_data_access.search_users(query)
        matching_users_not_friends = []
        for user in matching_users:
            friendship_data_access = current_app.config.get('friendship_data_access')
            if not friendship_data_access.get_friendship(current_user, user):
                matching_users_not_friends.append(user)
    else:
        matching_users_not_friends = []
    return render_template('friends/friends_search_results.html', users=matching_users_not_friends, app_data=config_data)


@friends_blueprint.route('/add_friend/<string:friend_name>', methods=['POST'])
@login_required
def add_friend(friend_name):
    """
    Handles POST requests for adding a friend
    :param friend_name: The name of the friend
    :return: Redenders the dashboard view
    """
    user_data_access = current_app.config.get('user_data_access')
    user_1 = user_data_access.get_user(current_user.username)
    user_2 = user_data_access.get_user(friend_name)
    friendship_data_access = current_app.config.get('friendship_data_access')
    friendship_data_access.add_friendship(Friendship(user_1, user_2))

    return render_template('friends/dashboard.html',  app_data=config_data)

@friends_blueprint.route('/add_message', methods=['POST'])
@login_required
def add_message():
    """
    Handles POST requests for adding a message
    """
    chatmessage_data_access = current_app.config.get('chatmessage_data_access')
    data = request.get_json()
    sender = current_user.username
    receiver = data['receiver']
    message = data['message']
    # Assuming the add_message method returns a boolean indicating success
    if chatmessage_data_access.add_message(ChatMessage(sender, receiver, message)):
        return jsonify({'status': 'success', 'message': 'Message sent successfully.'})
    else:
        return jsonify({'status': 'error', 'message': 'Failed to send message.'}), 500

@friends_blueprint.route('/visit_friend_world/<string:friend_name>', methods=['GET'])
@login_required
def visit_friend(friend_name):
    """
    Renders the visit friend view, for a user. This allows the user to visit a friend's world.
    """
    user_data_access = current_app.config.get('user_data_access')
    friend = user_data_access.get_user(friend_name)

    return render_template('friends/visit_friend.html', friend=friend, app_data=config_data)

src/ProgDBTutor/views/game.py
from flask import Blueprint, render_template, current_app, request, jsonify
from flask_login import login_required, current_user

from models.building import Building
from models.market import Market
from datetime import datetime, timedelta
import random
import json

from config import config_data

game_blueprint = Blueprint('game', __name__, template_folder='templates')

@game_blueprint.route('/')
@login_required
def game():
    """
    Renders the game view.
    :return:
    """
    return render_template('game/game.html', app_data=config_data)

@game_blueprint.route('/leaderboard')
@login_required
def leaderboard():
    """
    Renders the leaderboard view.
    :return:
    """
    return render_template('game/leaderboard.html', app_data=config_data)
@game_blueprint.route('/silo')
@login_required
def silo():
    """
    Renders the silo view.
    :return:
    """
    return render_template('silo.html', app_data=config_data)

@game_blueprint.route('/barn')
@login_required
def barn():
    """
    Renders the barn view.
    :return:
    """
    return render_template('barn.html', app_data=config_data)

@game_blueprint.route('/townhall')
@login_required
def townhall():
    """
    Renders the townhall view.
    :return:
    """
    return render_template('townhall.html', app_data=config_data)

@game_blueprint.route('/exploration')
@login_required
def exploration():
    """
    Renders the EXPLORATION  view.
    """
    return render_template('exploration/exploration.html', app_data=config_data)

@game_blueprint.route('/gifts')
@login_required
def gifts():
    """
    Renders the gifts view with the current user's gifts.
    The gifts are based on the user's last login time and the time the user has been playing the game.
    :return: Rendered template for the gifts view.
    """
    user_data_access = current_app.config.get('user_data_access')
    user = user_data_access.get_user(current_user.username)
    if user.last_gift is None:
        user.last_gift = datetime.now()

    gifts = {
        "Money": 200,
        "Wheat": 58,
        "Carrot": 47,
        "corn": 45,
        "Lettuce": 40,
        "Tomato": 35,
        "Turnip": 67,
        "zucchini": 50,
        "Parsnip": 60,
        "Cauliflower": 55,
        "eggplant": 45,
        "egg": 22,
        "Rustic egg": 37,
        "Crimson egg": 55,
        "Emerald egg": 11,
        "Sapphire egg": 55,
        "milk": 55,
        "Chocolate milk": 55,
        "Strawberry milk": 8,
        "Soy milk": 8,
        "Blueberry milk": 4,
    }

    gift = None
    amount = 0

    # Check if the user has logged in within the last hour
    if user.last_gift + timedelta(hours=1) <= datetime.now():
        # Calculate bonuses based on the time the user has been playing the game
        delta_created_at = datetime.now() - user.created_at
        delta_last_gift = datetime.now() - user.last_gift

        # Determine bonus multipliers
        # Example bonus logic (you can customize this logic as needed)
        time_played_bonus = max(delta_created_at.days // 30, 1)  # 1 bonus point for each month played
        recent_login_bonus = max((60 - delta_last_gift.seconds // 60), 1)  # Up to 60 bonus points for recent login

        # Pick a random gift and calculate the total amount with bonuses
        gift = random.choice(list(gifts.keys()))
        base_amount = gifts[gift]
        amount = base_amount + time_played_bonus + recent_login_bonus

        # Insert it in the database
        resource_data_access = current_app.config.get('resource_data_access')
        print(current_user.username, gift, amount)
        resource_data_access.update_resource(current_user.username, gift, amount)

        # Update the last gift time
        user_data_access.update_last_gift(current_user.username)

    return render_template('gifts.html', app_data=config_data, gift=gift, amount=amount)


"""
Building fetch and update functions
"""
def building_user_exists(buildings, id):
    for building in buildings:
        if building.building_id == id:
            return building
    return None

@game_blueprint.route('/update-building-map', methods=['POST'])
def update_map():
    """
    Handles POST requests to insert JSON data into the database.
    Expects JSON data in the request body.
    """
    try:
        building_data_access = current_app.config.get('building_data_access')

        # Parse JSON data from request body
        json_data = request.json
        building_information = json_data["building_information"]

        username_owner = current_user.username
        buildings = building_data_access.get_buildings_by_username_owner(username_owner)

        for building_info in building_information.values():
            building_type = building_info["general_information"]
            level = building_info["level"]
            augment_level = building_info.get("augment_level", 0)  # Default to 0 if not provided
            unlock_level = building_info.get("unlock_level", 0)  # Default to 0 if not provided
            created_at = datetime.now()
            x_value = building_info["building_location"][0]
            y_value = building_info["building_location"][1]
            building_id = building_info["self_key"]

            building = next((b for b in buildings if b.building_id == building_id), None)

            if building:
                # Update the existing building entry
                building.building_type = building_type
                building.level = level
                building.augment_level = augment_level
                building.unlock_level = unlock_level
                building.created_at = created_at
                building.x = x_value
                building.y = y_value
                building_data_access.add_building(building)

            else:
                # Insert a new building entry
                new_building = Building(building_id, username_owner, building_type, unlock_level, level, x_value, y_value, created_at, augment_level)
                building_data_access.add_building(new_building)

        return jsonify({"status": "success", "message": "Data inserted successfully"})
    except Exception as e:
        return jsonify({"status": "error", "message": str(e)}), 500


"""
Markt fetch and update functions
"""
def update_price(last_count, current_count, last_price, base_price):
    if last_price == base_price or current_count == base_price*3:
        last_price = base_price*2
    # Calculate the ratio of current count to last count
    count_ratio = current_count / last_count if last_count != 0 else 1
    if count_ratio >= 1:
        numb = [0.7,0.8,0.9]
        random_factor = numb[random.randint(0, 2)]
    else:
        numb = [1.1, 1.2, 1.3]
        random_factor = numb[random.randint(0, 2)]

    # Calculate the new price
    new_price = last_price * random_factor

    # Ensure the price is within the specified range
    new_price = max(base_price, min(base_price*3, round(new_price)))

    # return jsonify({"count_ratio": count_ratio, "random_factor" : random_factor, "new_price" : new_price})
    return new_price

@game_blueprint.route('/update-market', methods=['POST'])
def update_market():
    """
    Handles POST requests to insert market count data into the database.
    Expects crop name and sale amount in the request body as JSON.
    """
    try:
        # Get the crop name and sale amount from the request body
        json_data = request.json
        crop_name = json_data["crop"]
        sale = json_data["sale"]
        base_price = json_data["base_price"]

        # Get current market data
        market_data_access = current_app.config.get('market_data_access')
        market = market_data_access.get_market_data(crop_name)

        if market:
            # Update the last update time

            # Check if more than 1 minute has passed since the last update
            if  datetime.now() - market.last_update > timedelta(minutes=1):
                market.last_update = datetime.now()

                last_count = market.prev_quantity_crop
                current_count = market.current_quantity_crop
                last_price = market.current_price
                new_price = update_price(last_count, current_count, last_price, base_price)

                # Update prev_quantity_crop and reset current_quantity_crop

                market.prev_quantity_crop = market.current_quantity_crop
                market.current_quantity_crop = 0

                # change the price based on sales and random variable

                market.current_price = new_price

            # Update the existing market entry
            market.current_quantity_crop += sale
            market_data_access.add_market_data(market)
        else:
            # No existing market data found, create a new entry with crop's base price
            new_market = Market(crop_name, base_price, sale, 0, datetime.now())
            market_data_access.add_market_data(new_market)

        return jsonify({"status": "success", "message": "Market data updated successfully"})

    except Exception as e:
        return jsonify({"status": "error", "message": str(e)}), 500



@game_blueprint.route('/fetch-crop-price', methods=['GET'])
def fetch_crop_price():
    try:
        # Get the crop name from the query parameters
        crop_name = request.args.get('crop')
        base_price = request.args.get('base_price')
        if not isinstance(base_price, int):
            base_price = int(request.args.get('base_price'))


        # Query the database to fetch the price of the crop from the market
        market_data_access = current_app.config.get('market_data_access')
        market = market_data_access.get_market_data(crop_name)

        if market:
            # If market data exists for the crop, return its price
            if  datetime.now() - market.last_update > timedelta(minutes=4):
                market.last_update = datetime.now()

src/ProgDBTutor/templates/admin.html
<html>
<head>
    <title>{{ app_data['app_name'] }} - Admin Dashboard</title>
     <script type="module" src="{{ url_for('static', filename='js/settings.js') }}"></script>
     <script type="module" src="{{ url_for('static', filename='js/sound.js') }}"></script>
    {% include 'head.html' %}

</head>
<body>
    {% include 'header&footer.html' %}

    <div class="container-fluid mt-5">
        <div class="row justify-content-center">
            <div class="col-md-10 text-center">
                <h1>Admin Dashboard</h1>

                <!-- User State Section -->
                <div class="user-state-section my-4">
                    <h2>Users</h2>
                    <!-- Link to Users API -->
                    <div>
                        <a href="/api/users">Access Users API</a>
                    </div>
                </div>

                <!-- Map State Section -->
                <div class="map-state-section my-4">
                    <h2>Maps</h2>
                    <!-- Link to Maps API -->
                    <div>
                        <a href="/api/maps">Access Maps API</a>
                    </div>
                </div>

                <!-- Test Section -->
                <div class="map-state-section my-4">
                    <h2>Tests</h2>
                    <div class="text-center">
                        <!-- Add a button to run tests -->
                        <a href="{{ url_for('jasmine_tests') }}">
                            <button id="run-tests-btn" class="btn btn-primary">Run Tests</button>
                        </a>
                    </div>
                    <!-- Placeholder for Jasmine test results -->
                    <div id="jasmine-container"></div>
                </div>

                <!-- API Test Section
                <div class="api-test-section my-4">
                    <h2>Test API Requests</h2>
                    <p>Use the form below to test API requests.</p>
                    <form id="api-test-form">
                        <div class="mb-3">
                            <label for="api-endpoint" class="form-label">API Endpoint</label>
                            <input type="text" class="form-control" id="api-endpoint" placeholder="/api/users">
                        </div>
                        <div class="mb-3">
                            <label for="api-method" class="form-label">Method</label>
                            <select class="form-select" id="api-method">
                                <option>GET</option>
                                <option>POST</option>
                                <option>PUT</option>
                                <option>DELETE</option>
                            </select>
                        </div>
                        <div class="mb-3">
                            <label for="api-body" class="form-label">Request Body (JSON)</label>
                            <textarea class="form-control" id="api-body" rows="3"></textarea>
                        </div>
                        <button type="submit" class="btn btn-primary">Send Request</button>
                    </form>
                </div> -->

                <div class="my-3">
                    <a href="{{ url_for('auth.logout') }}">Logout</a>
                </div>
            </div>
        </div>
    </div>



    {% include 'footer.html' %}
</body>
</html>

src/ProgDBTutor/templates/barn.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ app_data['app_name'] }} - Barn</title>
    <link rel="stylesheet" href="../static/css/barn&silo.css">
    <link rel="icon" href="../static/img/ico/happy.ico" type="image/x-icon" id="favicon">
    <link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap" rel="stylesheet">
</head>
<body>
{% include 'header&footer.html' %}
<div class="ui-container">
    <div class="limit" id="limit"></div>
    <div class="description" id="description"></div>
    <div class="items" id="items"></div>
    <div class="scrap-button-field">
        <button class="scrap-button" id="scrap-btn">
            <img src="../static/img/UI/scrap_btn.png" alt="scrap" id="scrap" draggable="false">
        </button>
    </div>
    <div class="scrap-input">
        <button id="min" class="input-button">
            <img src="../static/img/UI/left_btn.png" alt="max" id="left" title="minimum" draggable="false">
        </button>
        <button id="decrease" class="input-button">
            <img src="../static/img/UI/minus_btn.png" alt="-" id="minus" title="decrease" draggable="false">
        </button>
        <input type="number" id="scrap-quantity" min="0" value="0" max="0" draggable="false">
        <button id="increase" class="input-button">
            <img src="../static/img/UI/plus_btn.png" alt="+" id="plus" title="increase" draggable="false">
        </button>
        <button id="max" class="input-button">
            <img src="../static/img/UI/right_btn.png" alt="max" id="right" title="maximum" draggable="false">
        </button>
    </div>
</div>
<script src="../static/js/buildingUI/barn.js"></script>
</body>
</html>

src/ProgDBTutor/templates/exploration.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>test html</title>
  <link rel="stylesheet" href="../static/css/explore.css">
</head>
<body>
{% include 'header&footer.html' %}
<div class="exploration" id="before-exploration">
    <div class="animal-list">
        <div class="animal">
            <img src="../static/img/assets/animals/Chicken/Chicken.1.png" class="animal-img" alt="Chicken" title="Chicken" draggable="false">
            <div class="quantity-selector">
                <button class="quantity-button" id="Decrease-Chicken">
                    <img src="../static/img/UI/minus_btn.png" alt="-" draggable="false">
                </button>
                <input class="input-container" type="number" id="Chicken" value="0" min="0">
                <button class="quantity-button" id="Increase-Chicken">
                    <img src="../static/img/UI/plus_btn.png" alt="+" draggable="false">
                </button>
            </div>
        </div>

        <div class="animal">
            <img src="../static/img/assets/animals/Cow/Cow.1.png" class="animal-img" alt="Cow" title="Cow" draggable="false">
            <div class="quantity-selector">
                <button class="quantity-button" id="Decrease-Cow">
                    <img src="../static/img/UI/minus_btn.png" alt="-"  draggable="false">
                </button>
                <input class="input-container" type="number" id="Cow" value="0" min="0">
                <button class="quantity-button" id="Increase-Cow">
                    <img src="../static/img/UI/plus_btn.png" alt="+"  draggable="false">
                </button>
            </div>
        </div>

        <div class="animal">
            <img src="../static/img/assets/animals/Pig/Pig.1.png" class="animal-img" alt="Pig" title="Pig" draggable="false">
            <div class="quantity-selector">
                <button class="quantity-button" id="Decrease-Pig">
                    <img src="../static/img/UI/minus_btn.png" alt="-" draggable="false">
                </button>
                <input class="input-container" type="number" id="Pig" value="0" min="0">
                <button class="quantity-button" id="Increase-Pig">
                    <img src="../static/img/UI/plus_btn.png" alt="+"  draggable="false">
                </button>
            </div>
        </div>

        <div class="animal">
            <img src="../static/img/assets/animals/Goat/Goat.1.png" class="animal-img" alt="Goat" title="Goat" draggable="false">
            <div class="quantity-selector">
                <button class="quantity-button"  id="Decrease-Goat">
                    <img src="../static/img/UI/minus_btn.png" alt="-" draggable="false">
                </button>
                <input class="input-container" type="number" id="Goat" value="0" min="0">
                <button class="quantity-button" id="Increase-Goat">
                    <img src="../static/img/UI/plus_btn.png" alt="+" draggable="false">
                </button>
            </div>
        </div>

    </div>

    <div class="perk-list">
        Perks
    </div>

    <div class="explore">
        <select id="exploration-time" class="exploration-time">
            <option value="1">1 minute</option>
            <option value="20">20 minutes</option>
            <option value="60">1 hour</option>
            <option value="180">3 hours</option>
            <option value="720">12 hours</option>
            <option value="1440">1 day</option>
        </select>
        <button class="explore-btn" id="explore-btn">
            <img src="../static/img/UI/big_explore_btn.png" alt="explore" draggable="false">
        </button>
    </div>
</div>
<div class="exploration" id="during-exploration"></div>
<div class="exploration" id="after-exploration"></div>
<script src="../static/js/explore.js"></script>
</body>
</html>

src/ProgDBTutor/templates/settings.html
<!DOCTYPE html>
<head>
    <title>{{ app_data['app_name'] }}</title>
    {% include 'head.html' %}
    <link rel="stylesheet" href="../static/css/settings.css"> <!--or different image -->


</head>
<html lang="en">
<body>
    {% include 'header&footer.html' %}

    <div class="center-wrapper">
    <img src="../static/img/UI/Settings_tab.png">
</div>

    <div class="container">
        <div class="row">
            <div class="col">
                LOG-OUT
            </div>
            <div class="col-auto">
                <div class="logout-btn"></div>
                <button class="sound-image-button" >
                    <a href="{{ url_for('auth.logout') }}">
                        <img src="../static/img/UI/logout_btn.png" alt="Logout" usemap="#logoutMap" id= "image-button">
                    </a>
                </button>
            </div>
        </div>


        <div class="row">
            <div class="col">
                SOUND
            </div>
            <div class="col-auto">
                <div class="sound-btn"></div>
                <button  class="sound-image-button" id="sounddown" ><img src="../static/img/UI/sounddown_btn.png" id="sounddownimg"></button>
                <span>&nbsp;</span>
                <p id="soundNumber"> 50 </p>
                <p> % </p>
                <span>&nbsp;</span>
                <button class="sound-image-button" id="soundup" ><img src="../static/img/UI/soundup_btn.png" id="soundupimg"></button>

            </div>
        </div>

        <div class="row">
            <div class="col">
                MUTE
            </div>
            <div class="col-auto">
               <div class="mute-btn"></div>
                <button  class="sound-image-button" id="muteButton"> <img src="../static/img/UI/sound_btn.png" id="mutebuttonimg"></button>
            </div>
        </div>


        <div class="row">
            <div class="col">
                BACKGROUND SOUND
            </div>
            <div class="col-auto">
               <div class="mute-btn"></div>
                <button class="sound-image-button" id="playBackgroundMusicButton"><img src="../static/img/UI/slider_off.png" id="backsoundimg" ></button>

            </div>
        </div>

        <div class="row">
            <div class="col">
                ZOOM
            </div>
            <div class="col-auto">
                <div class="zoom-btn"></div>
                <button class="sound-image-button" id="zoomDownButton"><img src="../static/img/UI/minus_btn.png" id="zoomdownimg" ></button>
                <span>&nbsp;</span>
                <p id="zoomNumber"> 50 </p>
                <p>% </p>
                <span>&nbsp;</span>
                <button class="sound-image-button" id="zoomUpButton"><img src="../static/img/UI/plus_btn.png" id="zoomupimg"></button>
            </div>
        </div>

        <div class="row">
            <div class="col">
                GAME OVERVIEW
            </div>
            <div class="col-auto">
                <div class="game-aspects-btn"></div>
                <button class="sound-image-button">
                    <a href="{{ url_for('book') }}">
                        <img src="../static/img/UI/question_btn.png" alt="Book" id="game-aspects-button">
                    </a>
                </button>
            </div>
        </div>

    </div>

    <script type="module" src="{{ url_for('static', filename='js/settings.js') }}"></script>
    <script type="module" src="{{ url_for('static', filename='js/sound.js') }}"></script>
    <script type="module" src="{{ url_for('static', filename='js/zoom.js') }}"></script>


    <script type="module" src="{{ url_for('static', filename='js/canvas.js') }}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/howler/2.2.3/howler.min.js"></script>
</body>
</html>

src/ProgDBTutor/templates/townhall.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ app_data['app_name'] }} - Townhall</title>
    <link rel="stylesheet" href="../static/css/townhall.css">
    <link rel="icon" href="../static/img/ico/happy.ico" type="image/x-icon" id="favicon">
    <link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap" rel="stylesheet">
</head>
{% include 'header&footer.html' %}
<body>
<div class="slider-container">
    <input type="range" min="0" max="10" value="1" class="slider" id="slider">
    <div class="slide-container" id="slides">
        <div class="slide" data-level="0" id="slide-0">Level 0 Unlocks<hr></div>
        <div class="slide" data-level="1" id="slide-1">Level 1 Unlocks<hr></div>
        <div class="slide" data-level="2" id="slide-2">Level 2 Unlocks<hr></div>
        <div class="slide" data-level="3" id="slide-3">Level 3 Unlocks<hr></div>
        <div class="slide" data-level="4" id="slide-4">Level 4 Unlocks<hr></div>
        <div class="slide" data-level="5" id="slide-5">Level 5 Unlocks<hr></div>
        <div class="slide" data-level="6" id="slide-6">Level 6 Unlocks<hr></div>
        <div class="slide" data-level="7" id="slide-7">Level 7 Unlocks<hr></div>
        <div class="slide" data-level="8" id="slide-8">Level 8 Unlocks<hr></div>
        <div class="slide" data-level="9" id="slide-9">Level 9 Unlocks<hr></div>
        <div class="slide" data-level="10" id="slide-10">Level 10 Unlocks<hr></div>
    </div>
</div>
<div class="stats-container" id="stats">
    <div class="stat-column">
        <div class="stat"></div> <!-- ATK -->
        <div class="stat"></div> <!-- DEF -->
    </div>
    <div class="stat-column">
        <div class="stat"></div> <!-- LVL -->
        <div class="stat"></div> <!-- COINS -->
    </div>
    <div class="gifts">
        <button id="gift-btn" class="gift-button">
             <a href="{{ url_for('game.gifts') }}">
                <img src="../static/img/UI/gifts_btn.png" alt="gifts" id="gift-img" title="view gifts" draggable="false">
            </a>
        </button>
    </div>
</div>

</div>

<script type="module" src="../static/js/buildingUI/townhall.js"></script>

</body>
</html>