src/ProgDBTutor/views/attack.py
from flask import Blueprint, render_template, current_app, session
from flask_login import login_required, current_user
from config import config_data
from .api import user_stats

attack_blueprint = Blueprint('attack', __name__, template_folder='templates')


@attack_blueprint.route('/visit_opponents_world')
@login_required
def visit_opponent():
    """
    Renders the attack view to render the opponent's world.
    """
    opponent = choose_opponent_logic()
    if not opponent:
        session.pop('previously_searched', None)  # Clear session if no opponent found
        return render_template('attack/no_opponent.html', app_data=config_data)
    return render_template('attack/visit_opponents_world.html', opponent=opponent, app_data=config_data)


def choose_opponent_logic():
    """
    Selects an opponent based on specified criteria.
    """
    user_data_access = current_app.config.get('user_data_access')
    friendship_data_access = current_app.config.get('friendship_data_access')

    users = user_data_access.get_all_users()
    users = [user for user in users if user.username != 'admin']

    friends = friendship_data_access.get_friends(current_user)
    friends_usernames = {friend.user2 if friend.user1 == current_user.username else friend.user1 for friend in friends}

    previously_searched = set(session.get('previously_searched', []))
    scores = {user.username: user_stats(user.username)['attack' if user == current_user else 'defense'] for user in
              users}

    eligible_users = [user for user in users if
                      user.username not in previously_searched and user.username != current_user.username and user.username not in friends_usernames and abs(
                          scores[current_user.username] - scores[user.username]) < 1000]

    sorted_eligible_users = sorted(eligible_users, key=lambda user: scores[user.username], reverse=True)
    if sorted_eligible_users:
        session['previously_searched'] = list(previously_searched | {sorted_eligible_users[0].username})
        return sorted_eligible_users[0]
    return None


@attack_blueprint.route('/attack_animation')
@login_required
def attack_animation():
    """
    Renders the attack animation view.
    """
    return render_template('attack/attack_animation.html', app_data=config_data)


@attack_blueprint.route('/attack_result')
@login_required
def attack_result():
    """
    Renders the attack result view.
    """
    previously_searched = session.get('previously_searched', [])
    if previously_searched:
        opponent = previously_searched[-1]
        result, resources = choose_result_logic(user_stats(opponent)['defense'],
                                                user_stats(current_user.username)['attack'], opponent)

        resource_data_access = current_app.config.get('resource_data_access')
        for resource, amount in resources.items():
            resource_data_access.update_resource(current_user.username, resource, amount)
            resource_data_access.update_resource(opponent, resource, -amount)

        return render_template('attack/attack_result.html', result=result, resources=resources, app_data=config_data)
    return render_template('attack/no_opponent.html', app_data=config_data)


import random


def choose_result_logic(opponent_score, player_score, opponent):
    """
    Determines the outcome of an attack based on scores.
    """
    major_difference_threshold = 1000
    score_difference = opponent_score - player_score

    if score_difference > major_difference_threshold:
        outcome = 'Lose'
    elif score_difference < -major_difference_threshold:
        outcome = 'Win'
    else:
        outcome = 'Win' if random.choice([0, 1]) == 1 else 'Lose'

    resource_data_access = current_app.config.get('resource_data_access')
    opponent_resources = {resource.resource_type: resource.amount for resource in resource_data_access.get_resources(opponent)}
    resources = {}
    percentage = random.uniform(0.05, 0.10)

    for resource, quantity in opponent_resources.items():
        change_amount = int(quantity * percentage * (1.25 if outcome == 'Win' else -1))
        if change_amount != 0:
            resources[resource] = change_amount

    return (outcome, resources)

src/ProgDBTutor/views/game.py
from flask import Blueprint, render_template, current_app, request, jsonify
from flask_login import login_required, current_user

from models.building import Building
from models.market import Market
from datetime import datetime, timedelta
import random
import json

from config import config_data

game_blueprint = Blueprint('game', __name__, template_folder='templates')

@game_blueprint.route('/')
@login_required
def game():
    """
    Renders the game view.
    :return:
    """
    return render_template('game/game.html', app_data=config_data)

@game_blueprint.route('/leaderboard')
@login_required
def leaderboard():
    """
    Renders the leaderboard view.
    :return:
    """
    return render_template('game/leaderboard.html', app_data=config_data)
@game_blueprint.route('/silo')
@login_required
def silo():
    """
    Renders the silo view.
    :return:
    """
    return render_template('silo.html', app_data=config_data)

@game_blueprint.route('/barn')
@login_required
def barn():
    """
    Renders the barn view.
    :return:
    """
    return render_template('barn.html', app_data=config_data)

@game_blueprint.route('/townhall')
@login_required
def townhall():
    """
    Renders the townhall view.
    :return:
    """
    return render_template('townhall.html', app_data=config_data)

@game_blueprint.route('/exploration')
@login_required
def exploration():
    """
    Renders the EXPLORATION  view.
    """
    return render_template('exploration/exploration.html', app_data=config_data)

@game_blueprint.route('/gifts')
@login_required
def gifts():
    """
    Renders the gifts view with the current user's gifts.
    The gifts are based on the user's last login time and the time the user has been playing the game.
    :return: Rendered template for the gifts view.
    """
    user_data_access = current_app.config.get('user_data_access')
    user = user_data_access.get_user(current_user.username)
    if user.last_gift is None:
        user.last_gift = datetime.now()

    gifts = {
        "Money": 200,
        "Wheat": 58,
        "Carrot": 47,
        "corn": 45,
        "Lettuce": 40,
        "Tomato": 35,
        "Turnip": 67,
        "zucchini": 50,
        "Parsnip": 60,
        "Cauliflower": 55,
        "eggplant": 45,
        "egg": 22,
        "Rustic egg": 37,
        "Crimson egg": 55,
        "Emerald egg": 11,
        "Sapphire egg": 55,
        "milk": 55,
        "Chocolate milk": 55,
        "Strawberry milk": 8,
        "Soy milk": 8,
        "Blueberry milk": 4,
    }

    gift = None
    amount = 0

    # Check if the user has logged in within the last hour
    if user.last_gift + timedelta(hours=1) <= datetime.now():
        # Calculate bonuses based on the time the user has been playing the game
        delta_created_at = datetime.now() - user.created_at
        delta_last_gift = datetime.now() - user.last_gift

        # Determine bonus multipliers
        # Example bonus logic (you can customize this logic as needed)
        time_played_bonus = max(delta_created_at.days // 30, 1)  # 1 bonus point for each month played
        recent_login_bonus = max((60 - delta_last_gift.seconds // 60), 1)  # Up to 60 bonus points for recent login

        # Pick a random gift and calculate the total amount with bonuses
        gift = random.choice(list(gifts.keys()))
        base_amount = gifts[gift]
        amount = base_amount + time_played_bonus + recent_login_bonus

        # Insert it in the database
        resource_data_access = current_app.config.get('resource_data_access')
        print(current_user.username, gift, amount)
        resource_data_access.update_resource(current_user.username, gift, amount)

        # Update the last gift time
        user_data_access.update_last_gift(current_user.username)

    return render_template('gifts.html', app_data=config_data, gift=gift, amount=amount)


"""
Building fetch and update functions
"""
def building_user_exists(buildings, id):
    for building in buildings:
        if building.building_id == id:
            return building
    return None

@game_blueprint.route('/update-building-map', methods=['POST'])
def update_map():
    """
    Handles POST requests to insert JSON data into the database.
    Expects JSON data in the request body.
    """
    try:
        building_data_access = current_app.config.get('building_data_access')

        # Parse JSON data from request body
        json_data = request.json
        building_information = json_data["building_information"]

        username_owner = current_user.username
        buildings = building_data_access.get_buildings_by_username_owner(username_owner)

        for building_info in building_information.values():
            building_type = building_info["general_information"]
            level = building_info["level"]
            augment_level = building_info.get("augment_level", 0)  # Default to 0 if not provided
            unlock_level = building_info.get("unlock_level", 0)  # Default to 0 if not provided
            created_at = datetime.now()
            x_value = building_info["building_location"][0]
            y_value = building_info["building_location"][1]
            building_id = building_info["self_key"]

            building = next((b for b in buildings if b.building_id == building_id), None)

            if building:
                # Update the existing building entry
                building.building_type = building_type
                building.level = level
                building.augment_level = augment_level
                building.unlock_level = unlock_level
                building.created_at = created_at
                building.x = x_value
                building.y = y_value
                building_data_access.add_building(building)

            else:
                # Insert a new building entry
                new_building = Building(building_id, username_owner, building_type, unlock_level, level, x_value, y_value, created_at, augment_level)
                building_data_access.add_building(new_building)

        return jsonify({"status": "success", "message": "Data inserted successfully"})
    except Exception as e:
        return jsonify({"status": "error", "message": str(e)}), 500


"""
Markt fetch and update functions
"""
def update_price(last_count, current_count, last_price, base_price):
    if last_price == base_price or current_count == base_price*3:
        last_price = base_price*2
    # Calculate the ratio of current count to last count
    count_ratio = current_count / last_count if last_count != 0 else 1
    if count_ratio >= 1:
        numb = [0.7,0.8,0.9]
        random_factor = numb[random.randint(0, 2)]
    else:
        numb = [1.1, 1.2, 1.3]
        random_factor = numb[random.randint(0, 2)]

    # Calculate the new price
    new_price = last_price * random_factor

    # Ensure the price is within the specified range
    new_price = max(base_price, min(base_price*3, round(new_price)))

    # return jsonify({"count_ratio": count_ratio, "random_factor" : random_factor, "new_price" : new_price})
    return new_price

@game_blueprint.route('/update-market', methods=['POST'])
def update_market():
    """
    Handles POST requests to insert market count data into the database.
    Expects crop name and sale amount in the request body as JSON.
    """
    try:
        # Get the crop name and sale amount from the request body
        json_data = request.json
        crop_name = json_data["crop"]
        sale = json_data["sale"]
        base_price = json_data["base_price"]

        # Get current market data
        market_data_access = current_app.config.get('market_data_access')
        market = market_data_access.get_market_data(crop_name)

        if market:
            # Update the last update time

            # Check if more than 1 minute has passed since the last update
            if  datetime.now() - market.last_update > timedelta(minutes=1):
                market.last_update = datetime.now()

                last_count = market.prev_quantity_crop
                current_count = market.current_quantity_crop
                last_price = market.current_price
                new_price = update_price(last_count, current_count, last_price, base_price)

                # Update prev_quantity_crop and reset current_quantity_crop

                market.prev_quantity_crop = market.current_quantity_crop
                market.current_quantity_crop = 0

                # change the price based on sales and random variable

                market.current_price = new_price

            # Update the existing market entry
            market.current_quantity_crop += sale
            market_data_access.add_market_data(market)
        else:
            # No existing market data found, create a new entry with crop's base price
            new_market = Market(crop_name, base_price, sale, 0, datetime.now())
            market_data_access.add_market_data(new_market)

        return jsonify({"status": "success", "message": "Market data updated successfully"})

    except Exception as e:
        return jsonify({"status": "error", "message": str(e)}), 500



@game_blueprint.route('/fetch-crop-price', methods=['GET'])
def fetch_crop_price():
    try:
        # Get the crop name from the query parameters
        crop_name = request.args.get('crop')
        base_price = request.args.get('base_price')
        if not isinstance(base_price, int):
            base_price = int(request.args.get('base_price'))


        # Query the database to fetch the price of the crop from the market
        market_data_access = current_app.config.get('market_data_access')
        market = market_data_access.get_market_data(crop_name)

        if market:
            # If market data exists for the crop, return its price
            if  datetime.now() - market.last_update > timedelta(minutes=4):
                market.last_update = datetime.now()

src/ProgDBTutor/templates/attack/attack_animation.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Attack Animation - {{ app_data['app_name'] }}</title>
    <style>
        body, html {
            margin: 0;
            padding: 0;
            width: 100%;
            height: 100%;
            overflow: hidden;
            background-image: url("../../static/img/background/terrain.png"); /* Matching the game's background color */
            display: flex;
            justify-content: center;
            align-items: center;
            font-size: 35vw; /* Adjust the size of the emoji */
        }
        .sword {
            position: absolute;
            opacity: 0; /* Start with swords invisible */
            transform-origin: center;
        }
        #sword1 {
            transform: rotate(45deg);
        }
        #sword2 {
            transform: rotate(-45deg);
        }
    </style>
</head>
<body>
    <div id="sword1" class="sword">⚔️</div>
    <div id="sword2" class="sword">⚔️</div>

    <script>
        window.onload = function() {
            const sword1 = document.getElementById('sword1');
            const sword2 = document.getElementById('sword2');
            const keyframes = [
                { transform: 'scale(0)', opacity: 0 },
                { transform: 'scale(1)', opacity: 1 },
                { transform: 'scale(1)', opacity: 1, offset: 0.8 },
                { transform: 'scale(0)', opacity: 0 }
            ];
            const timing = {
                duration: 800,
                iterations: Infinity, // Animation will repeat indefinitely
                direction: 'alternate' // Alternate direction for a smooth continuous effect
            };
            sword1.animate(keyframes, timing);
            sword2.animate(keyframes, timing);

            // Redirect to attack.result.html after 10 seconds
            setTimeout(function() {
                window.location.href = 'attack_result';
            }, 5000); // Change 10000 to the number of milliseconds you want
        }
    </script>
</body>
</html>

src/ProgDBTutor/templates/attack/attack_result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Attack Results - {{ app_data['app_name'] }}</title>
    <link rel="stylesheet" type="text/css" href="../static/css/UI.css">
    <link rel="stylesheet" type="text/css" href="../static/css/leaderboard.css">
    {% include 'head.html' %}
     <style>
        .table-hover tbody tr td {
            border-top: 0px solid transparent !important;
        }
    </style>
</head>
<body>
{% include 'header&footer.html' %}
<div class="leaderboard">
    <h1 class="leaderboard-header">Attack Result: {{ result }}</h1>
    <div class="table-responsive">
        <table class="table table-hover">
            <thead class="table-custom-header">
                <tr>
                    <th>Resource Type</th>
                    <th>Amount Taken</th>
                </tr>
            </thead>
            <tbody>
                {% for resource, amount in resources.items() %}
                <tr>
                    <td>{{ resource }}</td>
                    <td>{{ amount }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<script>
    // Optional: Script to dynamically update or load results if they are fetched from an API
</script>

</body>
</html>

src/ProgDBTutor/templates/attack/no_opponent.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>No Opponent - {{ app_data['app_name'] }}</title>
    {% include 'head.html' %}
</head>
<body class="d-flex align-items-center justify-content-center text-center" style="height: 100vh;">
    {% include 'header&footer.html' %}

    <div class="container">
        <h1>No Opponent Available</h1>
        <p>Sorry, we could not find an opponent for you at this time. Please try again later.</p>
    </div>

</body>
</html>

src/ProgDBTutor/templates/attack/visit_opponents_UI.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="../../static/css/UI.css">
    <title>game UI</title>
</head>
<body>
    <header>
        <button id="resource-btn" class="resource-btn" onclick="clickResources()" style="left: 10px">
            <img src="../../static/img/UI/resource_btn.png" alt="🌱">
        </button>
        <div class="overlay" id="resource-overlay">
            <div class="popup">
                <!-- The resource amounts of the user will be inserted here dynamically -->
            </div>
        </div>
        <button id="attack-btn" class="attack-btn" style="bottom: auto; top: 10px;">
            <a href="{{ url_for('attack.attack_animation') }}">
                <img src="../../static/img/UI/attack_btn.png" alt="⚔️">
            </a>
        </button>

    </header>
    <script>
        let clickedResourceButton = false;

        function clickResources() {
            const resourceButton = document.getElementById('resource-btn');
            const overlay = document.getElementById('resource-overlay');

            overlay.style.display = clickedResourceButton ? 'none' : 'flex';
            resourceButton.querySelector('img').src = clickedResourceButton ? "../../static/img/UI/resource_btn.png" : "../../static/img/UI/resource_pbtn.png";
            clickedResourceButton = !clickedResourceButton;

            // Access the script tag
            const scriptTag = document.getElementById('dataScript');
            // Get the opponent's username stored in the data-opponent attribute
            const opponentUsername = scriptTag.getAttribute('data-opponent');
            console.log(opponentUsername);
            fetch(`/api/resources/${opponentUsername}`)
            .then(response => response.json())
            .then(data => {
                updateResources(data);
                //updateMoney(data); // Call a separate function to update money
            })
            .catch(error => {
                console.error('Error fetching resources:', error);
                document.querySelector('.popup').innerHTML = `<p>Error fetching resources. Please try again later.</p>`;
            });
        }

       function updateResources(resources) {
            const popupDiv = document.querySelector('.popup');
            let resourceHTML = '';
            const displayTypes = ['Wheat', 'Carrot', 'Corn', 'Lettuce', 'Tomato', 'Turnip', 'Zucchini', 'Parsnip', 'Cauliflower', 'Eggplant',];
            let money = 0
           resources.forEach(resource => {
               if (displayTypes.includes(resource.resource_type)) {
                   resourceHTML += `${getAmountDisplay(resource.amount, resource.resource_type)}${getImage(resource.resource_type)}`;
                  resourceHTML += `<img src="../../static/img/UI/display.extender.png" alt="" draggable="false">`.repeat(5);
               }else if(resource.resource_type === 'Money'){
                   money = resource.amount
               }
           });
            resourceHTML += `${getAmountDisplay(money, 'money')}`;


            popupDiv.innerHTML = `<img src="../../static/img/UI/display.left.short.png" alt="" draggable="false">` + resourceHTML
                + `<img src="../../static/img/UI/display.money.right.png" alt="" draggable="false">`;
        }
        function getAmountDisplay(amount, type){
            let value = amount.toString();

            let HTML = ''
            for (let i = 0; i < value.length; i++) {
                if(i === 4 && type !== 'money'){
                    HTML += `<img src="../../static/img/UI/display.+.png" alt="." draggable="false">`;
                    break;
                }
                HTML += `<img src="../../static/img/UI/display.${value[i]}.png" alt="${value[i]}" draggable="false">`;
            }
            return HTML
        }

        function getImage(resourceType) {
            switch(resourceType) {
                case 'Corn': return '<img src="../../static/img/UI/display.corn.png" alt="🌽">';
                case 'Carrot': return '<img src="../../static/img/UI/display.carrot.png" alt="🥕">';
                case 'Cauliflower': return '<img src="../../static/img/UI/display.cauliflower.png" alt="⚪🥦">';
                case 'Tomato': return '<img src="../../static/img/UI/display.tomato.png" alt="🍅">';
                case 'Eggplant': return '<img src="../../static/img/UI/display.eggplant.png" alt="🍆">';
                case 'Lettuce': return '<img src="../../static/img/UI/display.lettuce.png" alt="🥬">';
                case 'Wheat': return '<img src="../../static/img/UI/display.wheat.png" alt="🌾">';
                case 'Turnip': return '<img src="../../static/img/UI/display.turnip.png" alt="🟣🌱">';
                case 'Parsnip': return '<img src="../../static/img/UI/display.parsnip.png" alt="⚪🌱">';
                case 'Zucchini': return '<img src="../../static/img/UI/display.zucchini.png" alt="🥒">';
                case 'Money': return '<img src="../../static/img/UI/display.money.png" alt="🪙">';
                // Add more as needed
                default: return ''; // Default case if no symbol is matched
            }
        }
    </script>

    <footer style="display: flex; justify-content: space-between; align-items: end;">
        <a href="{{ url_for('game.game') }}" style="margin: 10px">
                <img src="../../static/img/UI/back_btn.png" alt="🏡">
        </a>
        <div class="copyright" style="left: auto; right: 10px; transform: none; margin: 10px;">
            &copy; Team3 – Universiteit Antwerpen - PPDB
        </div>
        <a href="{{ url_for('attack.visit_opponent') }}" style="margin: 10px">
                <img src="../../static/img/UI/right_btn.png" alt="⚔️">
        </a>
    </footer>

</body>
</html>

src/ProgDBTutor/templates/attack/visit_opponents_world.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Attacking {{ opponent['username'] }}'s World - {{ app_data['app_name'] }}</title>
    {% include 'head.html' %}
    <style>
        canvas {
            margin: 0;
            image-rendering: pixelated;
            position: absolute;
            top: 0;
            left: 0;
        }

        body {
            overflow: hidden;
            margin: 0;
        }

        #canvasContainer {
            position: relative;
        }

        #canvasContainer {
            position: relative;
        }

        #buildingCanvas {
            z-index: 2;
            <!--border: solid red;-->
        }
        #terrainCanvas {
            z-index: 1;
            <!--border: solid black;-->
        }

        /* Loading screen styles */
        #loadingScreen {
            position: fixed;
            width: 100%;
            height: 100%;
            background: rgba(0, 0, 0, 0.8);
            color: white;
            display: flex;
            justify-content: center;
            align-items: center;
            z-index: 1000;
            animation: backgroundPulse 3s infinite;
        }

        #loadingScreen h1 {
            color: white;
            animation: typing 4s steps(40, end) forwards, blink 0.75s step-end infinite;
            white-space: nowrap;
            overflow: hidden;
            border-right: 3px solid transparent;
        }

        @keyframes typing {
            from { width: 0; }
            to { width: 40ch; }
        }

        @keyframes blink {
            from, to { border-color: transparent; }
            50% { border-color: white; }
        }

        @keyframes backgroundPulse {
            0% { background-color: rgba(0, 0, 0, 0.8); }
            50% { background-color: rgba(0, 0, 0, 0.6); }
            100% { background-color: rgba(0, 0, 0, 0.8); }
        }

        .hidden {
            display: none !important;
        }

    </style>

</head>
<body>
    <!-- Loading Screen -->
    <div id="loadingScreen">
        <h1>Searching opponent. Please wait....</h1>
    </div>

    {% include 'attack/visit_opponents_UI.html' %} <!-- This would be a new include for the UI when visiting -->

    {% include 'game/pop-up.html' %}

    <div id="canvasContainer">
        <canvas id="uiCanvas"></canvas>
        <canvas id="cropCanvas"></canvas>
        <canvas id="buildingCanvas"></canvas>
        <canvas id="terrainCanvas"></canvas>
    </div>

    <!-- When visiting a opponent's world -->
    <script id="dataScript" type="module" data-opponent="{{ opponent['username'] | string }}" src="{{ url_for('static', filename='js/canvas.js') }}"></script>

    <script>
        // Attach friend to the window object to make it globally accessible
        window.friend = document.getElementById('dataScript').getAttribute('data-opponent');
        console.log(window.friend);
    </script>

    <script>
        function hideLoadingScreen() {
            document.getElementById('loadingScreen').classList.add('hidden');
        }
    </script>

</body>
</html>